### ISSUE TITLE
NPM Package out of Sync

### ISSUE THREAD

**Issue by chsegala** [ts-oas/ts-oas#10]
I think the NPM package is not synced with the latest additions.

- the `components` is not part of `OpenApiSpecData`
- `never` type is not recognized

I searched for `getSecurity` in `/ts-oas/dist/lib/TypescriptOAS.js` in https://www.npmjs.com/package/ts-oas?activeTab=code and got 0 results.

**Comment by alireza-mf** [comment]
You're right, v0.4.3's npm content was not updated. Just bumped a patch version!
