### ISSUE TITLE
Doesnt handle ts Records properly

### ISSUE THREAD

**Issue by kevinand11** [ts-oas/ts-oas#13]
Running getSchema over this type `Record<string, number>` results in `{ "type": "object" }`. 

This result is too restrictive especially when pairing with a package like fastify. 

Expected result should be `{ "type": "object", "additionalProperties": { "type": "number" } }`
One would expect the value type of the record to be used to generate a schema which is assigned to the `additionalProperties` of the result schema

**Comment by alireza-mf** [comment]
At the current state, if you add the @additionalProperties decorator to your type like this:
```
    /**
     * @additionalProperties
     */
    foo: Record<string, number>;
```
it will at least help to resolve the restrictiveness by allowing additional properties.

**Comment by kevinand11** [comment]
I opened a pr that resolves this [https://github.com/ts-oas/ts-oas/pull/18](https://github.com/ts-oas/ts-oas/pull/18)... Would love to get some immediate feedback @alireza-mf

**Comment by kevinand11** [comment]
@alireza-mf. Thanks for merging.. Noticed a new version of the package hasn't been published though in about 3 months, despite frequent changes

**Comment by alireza-mf** [comment]
Suree, I'll do it by tomorrow
