### ISSUE TITLE
Regular expression "/Api$/" breaks the program

### ISSUE THREAD

**Issue by james-hu** [ts-oas/ts-oas#15]
Changing this line in the "Get started" example:
```
const specObject = tsoas.getOpenApiSpec([/API$/]);
```
into
```
const specObject = tsoas.getOpenApiSpec([/Api$/]);
```
breaks the program. It ssems like there's something internal ending with "Api" and it could get picked up.

**Comment by james-hu** [comment]
Thanks. Making the regular expression more specific is my current workaround.
What about this, hard code the exclusion of those known internal types?

**Comment by james-hu** [comment]
Agree, it is more like a convenient workaround to make it less confusing to new users.
My current use case is to have both ApiMapper definitions and OAS generation code in the same file, like this:
```typescript
import TypescriptOAS, { ApiMapper, createProgram } from 'ts-oas';
... import my own APIs

type Security = [
  {
    ApiKey: [];
    JWT: [];
  },
];

/**
 * @summary Get order details.
 * @tags Orders
 */
export type OrdersGetDetailsApi = ApiMapper<{
...
}>;

...

const tsProgram = createProgram([path.basename(__filename)], path.join(__dirname, 'tsconfig.json'), path.resolve());
const spec = new TypescriptOAS(tsProgram, {
...
});

...

fs.writeFileSync(...);

```

Is there something like "@ignore" that you can add to internal types?

**Comment by alireza-mf** [comment]
`@ignore` [will work](https://github.com/ts-oas/ts-oas?tab=readme-ov-file#special-keywords-for-root-of-api-types) but there could be other sources that are imported, too, and mistakenly being considered ...

Perhaps the correct way is just look at the root files and access their imports:
```
sourceFile.statements.forEach((statement) => {
        if (ts.isImportDeclaration(statement)) {
```
instead of the current code (looking through all the program's source files):
```
protected buildSchemaGenerator(program: ts.Program, options: Options = {}) {
  ...
  program.getSourceFiles().forEach((sourceFile, _sourceFileIdx) => {
    ...
```

**Comment by james-hu** [comment]
It seems there are several approaches that could be useful, the choice could be choosing none, or one, or combination of several :

1. Leave it. Not a big deal for experienced developer; Could scare away inexperienced developers; Having it highlighted in documentation could be helpful.
2. Hard code (through @ignore or an interal lookup table) the exclusion of known internal types. It is considered as hard coding; It can't cover other types introduced by the consumers through other imports; However, it is a quick fix, won't affect other logic or introduce additinal complexity to the code base.
3. Add another setting about which shource code files to search for those types. It could be another regular expression or a glob, and only types defined in a file that its relative path matches this setting would be picked up for type name matching test. This gives the consumers enough flexibility; It is versatile; It supplements the existing type name matching logic. It provides backward compatibility.
4. Extend existing type name matching logic to allow the regular expression to cover file path matching. Similar to option 3 but there's only one setting to cover both file name matching and type name matching. Comparing with option 3, it is has more complexity in implementation (for implementing this feature) and utilisation (for writing the correct regexp for using this feature).
5. Hard code the logic to search only in files imported in a certain way (for example, imported in the "root" file only). It is also a kind of hard coding; It may forbid some use cases.
