### ISSUE TITLE
Values of "$ref" and component names are not encoded

### ISSUE THREAD

**Issue by james-hu** [ts-oas/ts-oas#16]
I've successfully generated the spec JSON file, and I uploaded it to https://editor.swagger.io/ for validation. These error messages are shown:

- $ref values must be RFC3986-compliant percent-encoded URIs
- Component names can only contain the characters A-Z a-z 0-9 - . _

I think they are caused by "$ref" values like these:

- 
- $ref: '#/components/schemas/{substitutions:Substitution[];}'
- type
    '{substitutions:Substitution[];}':

This happens when the type of the property is like this:
```
substitutions?: SubstituteStep['config']['substitutions'];
```

**Comment by alireza-mf** [comment]
I couldn't reproduce the issue with: `substitutions?: SubstituteStep['config']['substitutions'];` It ignores referring these kind of indexed type accesses, and put the whole schema in front of the property, which I think is fine.

could you share the all the types and output?

**Comment by alireza-mf** [comment]
I indeed tested with ref: true
It most likely related to [ignoreErrors which could generate incorrect schemas](https://github.com/ts-oas/ts-oas?tab=readme-ov-file#ignoreerrors) if there are syntax errors in ts code.
Let me know if that's the case.

**Comment by james-hu** [comment]
I found a way to reproduce it. Just need to append this into `common-interfaces.ts`:

```
// No change to the original content up to `statuses: STATUS[];`
  statuses: STATUS[];
  repairConfig: Repair['config'];
  damageFollowUps: FollowUp[];
}

declare enum ProcessingType {
  Discard = "discard",
  Repair = "repair",
}
interface AbstractProcessing<T extends ProcessingType, C> {
  type: T;
  config: C;
}


type Discard = AbstractProcessing<ProcessingType.Discard, { location: string }>;
type Repair = AbstractProcessing<ProcessingType.Repair, {
  repairer: string;
  estimatedCost: number;
  substitutions: Substitution[];
}>;

interface Substitution {
  from?: string;
  to: string;
}

type FollowUp = Discard | Repair;
``` 

Then just need to run the test case "should validate against SwaggerParser and json file with refs", and you will find these:

- #/components/schemas/{repairer:string;estimatedCost:number;substitutions:Substitution[];}
- #/components/schemas/{location:string;}

I think it is related to how fullTypeName is determined. It seems to be from:
```
else {
                fullTypeName = this.getTypeName(typ);
```

**Comment by alireza-mf** [comment]
Alright then, found out the problem is it falling into the if 15 lines after `fullTypeName` you mentioned, at `asRef = true;`.
